name: getbadge

on:
  push:
    branches:
      - '*'

  #schedule:
  #  # run CI at the end of every day https://jasonet.co/posts/scheduled-actions/
  #  - cron: "0 12 * * 1"

jobs:
  get-download-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install deps
        run: pip install numpy pandas

      - name: Get info
        run: |
          cd assets/
          curl "https://dataverse.no/api/info/metrics/filedownloads?parentAlias=ntnu"
          ls -haltr
          more "filedownloads?parentAlias=ntnu"
          python generate_badge.py
          ls -haltr
            